export const CABANG_LIST_REQUEST = 'CABANG_LIST_REQUEST'
export const CABANG_LIST_SUCCESS = 'CABANG_LIST_SUCCESS'
export const CABANG_LIST_FAIL = 'CABANG_LIST_FAIL'

export const CABANG_DETAILS_REQUEST = 'CABANG_DETAILS_REQUEST'
export const CABANG_DETAILS_SUCCESS = 'CABANG_DETAILS_SUCCESS'
export const CABANG_DETAILS_FAIL = 'CABANG_DETAILS_FAIL'

export const CABANG_DELETE_REQUEST = 'CABANG_DELETE_REQUEST'
export const CABANG_DELETE_SUCCESS = 'CABANG_DELETE_SUCCESS'
export const CABANG_DELETE_FAIL = 'CABANG_DELETE_FAIL'

export const CABANG_CREATE_REQUEST = 'CABANG_CREATE_REQUEST'
export const CABANG_CREATE_SUCCESS = 'CABANG_CREATE_SUCCESS'
export const CABANG_CREATE_FAIL = 'CABANG_CREATE_FAIL'
export const CABANG_CREATE_RESET = 'CABANG_CREATE_RESET'

export const CABANG_UPDATE_REQUEST = 'CABANG_UPDATE_REQUEST'
export const CABANG_UPDATE_SUCCESS = 'CABANG_UPDATE_SUCCESS'
export const CABANG_UPDATE_FAIL = 'CABANG_UPDATE_FAIL'
export const CABANG_UPDATE_RESET = 'CABANG_UPDATE_RESET'