export const KECAMATAN_LIST_REQUEST = 'KECAMATAN_LIST_REQUEST'
export const KECAMATAN_LIST_SUCCESS = 'KECAMATAN_LIST_SUCCESS'
export const KECAMATAN_LIST_FAIL = 'KECAMATAN_LIST_FAIL'

export const KECAMATAN_DETAILS_REQUEST = 'KECAMATAN_DETAILS_REQUEST'
export const KECAMATAN_DETAILS_SUCCESS = 'KECAMATAN_DETAILS_SUCCESS'
export const KECAMATAN_DETAILS_FAIL = 'KECAMATAN_DETAILS_FAIL'

export const KECAMATAN_DELETE_REQUEST = 'KECAMATAN_DELETE_REQUEST'
export const KECAMATAN_DELETE_SUCCESS = 'KECAMATAN_DELETE_SUCCESS'
export const KECAMATAN_DELETE_FAIL = 'KECAMATAN_DELETE_FAIL'

export const KECAMATAN_CREATE_REQUEST = 'KECAMATAN_CREATE_REQUEST'
export const KECAMATAN_CREATE_SUCCESS = 'KECAMATAN_CREATE_SUCCESS'
export const KECAMATAN_CREATE_FAIL = 'KECAMATAN_CREATE_FAIL'
export const KECAMATAN_CREATE_RESET = 'KECAMATAN_CREATE_RESET'

export const KECAMATAN_UPDATE_REQUEST = 'KECAMATAN_UPDATE_REQUEST'
export const KECAMATAN_UPDATE_SUCCESS = 'KECAMATAN_UPDATE_SUCCESS'
export const KECAMATAN_UPDATE_FAIL = 'KECAMATAN_UPDATE_FAIL'
export const KECAMATAN_UPDATE_RESET = 'KECAMATAN_UPDATE_RESET'