export const KELURAHAN_LIST_REQUEST = 'KELURAHAN_LIST_REQUEST'
export const KELURAHAN_LIST_SUCCESS = 'KELURAHAN_LIST_SUCCESS'
export const KELURAHAN_LIST_FAIL = 'KELURAHAN_LIST_FAIL'

export const KELURAHAN_DETAILS_REQUEST = 'KELURAHAN_DETAILS_REQUEST'
export const KELURAHAN_DETAILS_SUCCESS = 'KELURAHAN_DETAILS_SUCCESS'
export const KELURAHAN_DETAILS_FAIL = 'KELURAHAN_DETAILS_FAIL'

export const KELURAHAN_DELETE_REQUEST = 'KELURAHAN_DELETE_REQUEST'
export const KELURAHAN_DELETE_SUCCESS = 'KELURAHAN_DELETE_SUCCESS'
export const KELURAHAN_DELETE_FAIL = 'KELURAHAN_DELETE_FAIL'

export const KELURAHAN_CREATE_REQUEST = 'KELURAHAN_CREATE_REQUEST'
export const KELURAHAN_CREATE_SUCCESS = 'KELURAHAN_CREATE_SUCCESS'
export const KELURAHAN_CREATE_FAIL = 'KELURAHAN_CREATE_FAIL'
export const KELURAHAN_CREATE_RESET = 'KELURAHAN_CREATE_RESET'

export const KELURAHAN_UPDATE_REQUEST = 'KELURAHAN_UPDATE_REQUEST'
export const KELURAHAN_UPDATE_SUCCESS = 'KELURAHAN_UPDATE_SUCCESS'
export const KELURAHAN_UPDATE_FAIL = 'KELURAHAN_UPDATE_FAIL'
export const KELURAHAN_UPDATE_RESET = 'KELURAHAN_UPDATE_RESET'