export const KODEPOS_LIST_REQUEST = 'KODEPOS_LIST_REQUEST'
export const KODEPOS_LIST_SUCCESS = 'KODEPOS_LIST_SUCCESS'
export const KODEPOS_LIST_FAIL = 'KODEPOS_LIST_FAIL'

export const KODEPOS_DETAILS_REQUEST = 'KODEPOS_DETAILS_REQUEST'
export const KODEPOS_DETAILS_SUCCESS = 'KODEPOS_DETAILS_SUCCESS'
export const KODEPOS_DETAILS_FAIL = 'KODEPOS_DETAILS_FAIL'

export const KODEPOS_DELETE_REQUEST = 'KODEPOS_DELETE_REQUEST'
export const KODEPOS_DELETE_SUCCESS = 'KODEPOS_DELETE_SUCCESS'
export const KODEPOS_DELETE_FAIL = 'KODEPOS_DELETE_FAIL'

export const KODEPOS_CREATE_REQUEST = 'KODEPOS_CREATE_REQUEST'
export const KODEPOS_CREATE_SUCCESS = 'KODEPOS_CREATE_SUCCESS'
export const KODEPOS_CREATE_FAIL = 'KODEPOS_CREATE_FAIL'
export const KODEPOS_CREATE_RESET = 'KODEPOS_CREATE_RESET'

export const KODEPOS_UPDATE_REQUEST = 'KODEPOS_UPDATE_REQUEST'
export const KODEPOS_UPDATE_SUCCESS = 'KODEPOS_UPDATE_SUCCESS'
export const KODEPOS_UPDATE_FAIL = 'KODEPOS_UPDATE_FAIL'
export const KODEPOS_UPDATE_RESET = 'KODEPOS_UPDATE_RESET'