export const KOTA_LIST_REQUEST = 'KOTA_LIST_REQUEST'
export const KOTA_LIST_SUCCESS = 'KOTA_LIST_SUCCESS'
export const KOTA_LIST_FAIL = 'KOTA_LIST_FAIL'

export const KOTA_DETAILS_REQUEST = 'KOTA_DETAILS_REQUEST'
export const KOTA_DETAILS_SUCCESS = 'KOTA_DETAILS_SUCCESS'
export const KOTA_DETAILS_FAIL = 'KOTA_DETAILS_FAIL'

export const KOTA_DELETE_REQUEST = 'KOTA_DELETE_REQUEST'
export const KOTA_DELETE_SUCCESS = 'KOTA_DELETE_SUCCESS'
export const KOTA_DELETE_FAIL = 'KOTA_DELETE_FAIL'

export const KOTA_CREATE_REQUEST = 'KOTA_CREATE_REQUEST'
export const KOTA_CREATE_SUCCESS = 'KOTA_CREATE_SUCCESS'
export const KOTA_CREATE_FAIL = 'KOTA_CREATE_FAIL'
export const KOTA_CREATE_RESET = 'KOTA_CREATE_RESET'

export const KOTA_UPDATE_REQUEST = 'KOTA_UPDATE_REQUEST'
export const KOTA_UPDATE_SUCCESS = 'KOTA_UPDATE_SUCCESS'
export const KOTA_UPDATE_FAIL = 'KOTA_UPDATE_FAIL'
export const KOTA_UPDATE_RESET = 'KOTA_UPDATE_RESET'