export const OUTLET_LIST_REQUEST = 'OUTLET_LIST_REQUEST'
export const OUTLET_LIST_SUCCESS = 'OUTLET_LIST_SUCCESS'
export const OUTLET_LIST_FAIL = 'OUTLET_LIST_FAIL'

export const OUTLET_DETAILS_REQUEST = 'OUTLET_DETAILS_REQUEST'
export const OUTLET_DETAILS_SUCCESS = 'OUTLET_DETAILS_SUCCESS'
export const OUTLET_DETAILS_FAIL = 'OUTLET_DETAILS_FAIL'

export const OUTLET_DELETE_REQUEST = 'OUTLET_DELETE_REQUEST'
export const OUTLET_DELETE_SUCCESS = 'OUTLET_DELETE_SUCCESS'
export const OUTLET_DELETE_FAIL = 'OUTLET_DELETE_FAIL'

export const OUTLET_CREATE_REQUEST = 'OUTLET_CREATE_REQUEST'
export const OUTLET_CREATE_SUCCESS = 'OUTLET_CREATE_SUCCESS'
export const OUTLET_CREATE_FAIL = 'OUTLET_CREATE_FAIL'
export const OUTLET_CREATE_RESET = 'OUTLET_CREATE_RESET'

export const OUTLET_UPDATE_REQUEST = 'OUTLET_UPDATE_REQUEST'
export const OUTLET_UPDATE_SUCCESS = 'OUTLET_UPDATE_SUCCESS'
export const OUTLET_UPDATE_FAIL = 'OUTLET_UPDATE_FAIL'
export const OUTLET_UPDATE_RESET = 'OUTLET_UPDATE_RESET'