export const PROVINSI_LIST_REQUEST = 'PROVINSI_LIST_REQUEST'
export const PROVINSI_LIST_SUCCESS = 'PROVINSI_LIST_SUCCESS'
export const PROVINSI_LIST_FAIL = 'PROVINSI_LIST_FAIL'

export const PROVINSI_DETAILS_REQUEST = 'PROVINSI_DETAILS_REQUEST'
export const PROVINSI_DETAILS_SUCCESS = 'PROVINSI_DETAILS_SUCCESS'
export const PROVINSI_DETAILS_FAIL = 'PROVINSI_DETAILS_FAIL'

export const PROVINSI_DELETE_REQUEST = 'PROVINSI_DELETE_REQUEST'
export const PROVINSI_DELETE_SUCCESS = 'PROVINSI_DELETE_SUCCESS'
export const PROVINSI_DELETE_FAIL = 'PROVINSI_DELETE_FAIL'

export const PROVINSI_CREATE_REQUEST = 'PROVINSI_CREATE_REQUEST'
export const PROVINSI_CREATE_SUCCESS = 'PROVINSI_CREATE_SUCCESS'
export const PROVINSI_CREATE_FAIL = 'PROVINSI_CREATE_FAIL'
export const PROVINSI_CREATE_RESET = 'PROVINSI_CREATE_RESET'

export const PROVINSI_UPDATE_REQUEST = 'PROVINSI_UPDATE_REQUEST'
export const PROVINSI_UPDATE_SUCCESS = 'PROVINSI_UPDATE_SUCCESS'
export const PROVINSI_UPDATE_FAIL = 'PROVINSI_UPDATE_FAIL'
export const PROVINSI_UPDATE_RESET = 'PROVINSI_UPDATE_RESET'