export const WILAYAH_LIST_REQUEST = 'WILAYAH_LIST_REQUEST'
export const WILAYAH_LIST_SUCCESS = 'WILAYAH_LIST_SUCCESS'
export const WILAYAH_LIST_FAIL = 'WILAYAH_LIST_FAIL'

export const WILAYAH_DETAILS_REQUEST = 'WILAYAH_DETAILS_REQUEST'
export const WILAYAH_DETAILS_SUCCESS = 'WILAYAH_DETAILS_SUCCESS'
export const WILAYAH_DETAILS_FAIL = 'WILAYAH_DETAILS_FAIL'

export const WILAYAH_DELETE_REQUEST = 'WILAYAH_DELETE_REQUEST'
export const WILAYAH_DELETE_SUCCESS = 'WILAYAH_DELETE_SUCCESS'
export const WILAYAH_DELETE_FAIL = 'WILAYAH_DELETE_FAIL'

export const WILAYAH_CREATE_REQUEST = 'WILAYAH_CREATE_REQUEST'
export const WILAYAH_CREATE_SUCCESS = 'WILAYAH_CREATE_SUCCESS'
export const WILAYAH_CREATE_FAIL = 'WILAYAH_CREATE_FAIL'
export const WILAYAH_CREATE_RESET = 'WILAYAH_CREATE_RESET'

export const WILAYAH_UPDATE_REQUEST = 'WILAYAH_UPDATE_REQUEST'
export const WILAYAH_UPDATE_SUCCESS = 'WILAYAH_UPDATE_SUCCESS'
export const WILAYAH_UPDATE_FAIL = 'WILAYAH_UPDATE_FAIL'
export const WILAYAH_UPDATE_RESET = 'WILAYAH_UPDATE_RESET'